name: spec
on: [push, pull_request]
jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: |
        luarocks install --only-deps lua-ihex-dev-1.rockspec
    - name: Cache Lua machinery
      uses: actions/cache@v2
      with:
        path: |
          .install
          .lua
          .luarocks
        key: lua-${{ matrix.luaVersion }}-${{ hashFiles('lua-ihex-dev-1.rockspec', '.github/workflows/busted.yml') }}
    - name: Build
      run: |
        luarocks make
    - name: Run tests
      run: busted